import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Aside from "@/components/layouts/Aside";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${inter.variable} h-full bg-main-bg`}
    >
      <body className="h-full bg-main-bg flex">
        <Aside />
        <div className="flex flex-col w-full">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
